spring:
  datasource:
    url: jdbc:mysql://localhost:3306/product
    username: root
    password: itc801
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: update
    database: mysql
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  sql:
    init:
      mode: always
